### ISSUE TITLE
Reboots after SSMS install

### ISSUE THREAD

**Issue by packerphil** [Skatterbrainz/CMBuild#13]
Not really an issue, more of a note. There seems to be 2 reboots needed after the installation of SSMS.

**Comment by Skatterbrainz** [comment]
Build 1.0.7 has been modified to replace -NoReboot with -RestartMode of either "Prompt" or "Auto".  In addition, more checks have been added for pending restarts and handling of restarts based on $RestartMode.

**Comment by Skatterbrainz** [comment]
Needs testing and confirmation in 1.0.7
